
services:
  app:
    image: ${DOCKER_IMAGE}
    container_name: app_prod
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./credential.json:/instagram/credential.json:ro
    environment:
      - FLASK_APP=app.main
      - GOOGLE_APPLICATION_CREDENTIALS=/instagram/credential.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3