services:
  app:
    container_name: app_dev
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
      - 5678:5678
    environment:
      - FLASK_APP=app.main
      - FLASK_DEBUG=1
    volumes:
      - ./app:/instagram/app
      - ./alembic:/instagram/alembic
      - ~/.config/gcloud:/root/.config/gcloud:ro
    entrypoint: [
        'python',
        '-m',
        'debugpy',
        '--listen',
        '0.0.0.0:5678',
        # "--wait-for-client",
        '-m',
        'flask',
        'run',
        '--host=0.0.0.0',
        '--port=8000'
      ]
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/api/v1/health']
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - instagram

  mysql:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - instagram

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - instagram

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery
    entrypoint:
      [
        'celery',
        '-A',
        'app.celery_worker.celery',
        'worker',
        '--loglevel=info',
        '-c',
        '4'
      ]
    env_file:
      - .env
    volumes:
      - ./app:/instagram/app
    depends_on:
      - redis
    networks:
      - instagram

  celery_dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flower
    entrypoint:
      ['celery', '-A', 'app.celery_worker.celery', 'flower', '--port=5555']
    ports:
      - 5557:5555
    env_file:
      - .env
    volumes:
      - ./app:/instagram/app
    depends_on:
      - celery_worker
    networks:
      - instagram

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
  #   container_name: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #     - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
  #     - xpack.security.enabled=false
  #     - xpack.security.enrollment.enabled=false
  #   ports:
  #     - '9200:9200'
  #     - '9300:9300'
  #   volumes:
  #     - elasticsearch_data:/usr/share/elasticsearch/data
  #   restart: unless-stopped
  #   healthcheck:
  #     test:
  #       ['CMD-SHELL', 'curl -f http://localhost:9200/_cluster/health || exit 1']
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #   networks:
  #     - instagram

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.15.0
  #   container_name: kibana
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #     - xpack.security.enabled=false
  #   ports:
  #     - '5601:5601'
  #   depends_on:
  #     - elasticsearch
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ['CMD-SHELL', 'curl -f http://localhost:5601/api/status || exit 1']
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #   networks:
  #     - instagram

volumes:
  mysql_data:
  redis_data:
  # elasticsearch_data:

networks:
  instagram:
    external: true
