version: '3.9'

services:
  app:
    image: ${DOCKER_IMAGE}
    container_name: app_prod
    ports:
      - 8000:8000
    environment:
      - FLASK_APP=app.main
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/public"]
      interval: 30s
      timeout: 10s
      retries: 3
