"""Change status field in EmailJob

Revision ID: 9023ffb35fae
Revises: 43f21f046672
Create Date: 2026-01-09 03:55:08.205876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9023ffb35fae'
down_revision: Union[str, Sequence[str], None] = '43f21f046672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_job', sa.Column('is_sent', sa.String(length=10), nullable=True))
    op.drop_column('email_job', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_job', sa.Column('status', mysql.VARCHAR(length=10), nullable=True))
    op.drop_column('email_job', 'is_sent')
    # ### end Alembic commands ###
