"""Change Enum type of status

Revision ID: cc7dfe3a5efb
Revises: 95d7ad28d70d
Create Date: 2025-05-21 10:02:55.524887

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "cc7dfe3a5efb"
down_revision = "95d7ad28d70d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=mysql.ENUM("DRAFT", "PUBLIC"),
            type_=sa.Enum("DRAFT", "PUBLIC", name="poststatus", native_enum=False),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.Enum(
                "DRAFT", "PUBLIC", name="poststatus", native_enum=False
            ),
            type_=mysql.ENUM("DRAFT", "PUBLIC"),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
