# Event: On push → any branch except main

# Jobs:
#  - Build: Format code with Black Formatter
#  - Unit Test with matrix Python versions
# Description: This workflow will run for every commit on any branch except the main branch. It will build and then test the app with multiple Python versions.


name: Build and UnitTest

on:
  push:
    branches-ignore: [ main, develop ]

jobs:
  format:
    name: Black Formatter.
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Black
      run: pip install black

    - name: Lint with black
      run: black . --check

  # test:
  #   name: Test with Python ${{ matrix.python-version }}
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       python-version: ["3.8", "3.9", "3.10", "3.11"]

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4

  #   - name: Set up Python ${{ matrix.python-version }}
  #     uses: actions/setup-python@v4
  #     with:
  #       python-version: ${{ matrix.python-version }}

  #   - name: Install poetry
  #     uses: snok/install-poetry@v1

  #   - name: Install dependencies with Poetry
  #     run: poetry install

  #   - name: Run tests
  #     run: poetry run pytest