# Event: On push → develop/main

# Jobs:
#  - Build
#  - Test matrix → unnecessary if main is a protected branch
#  - Deploy
# Description:
# This workflow will trigger when a commit is pushed to develop/main or a pull request is merged/pushed. 
# It will build and then test the app with a test matrix → This step is unnecessary if main is a protected branch and you could only commit changed via Pull Request.
# Afterwards the docker image instagram:latest will be built and pushed to the image repository.

# We can separate deploy to develop and main to different workflows since they are different environments.

name: Deploy to Production

on:
  push:
    branches:
      - develop
      - main

jobs:

  build:
    name: Build and Push Docker Images
    runs-on: [self-hosted, V1]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/instagram
          tags: |
            sha-${{ github.sha }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

  deploy:
    name: Deploy to GCE
    runs-on: [self-hosted, V1]
    strategy:
      matrix:
        server: [V1, V2]
        include:
          - server: V1
            host: FLASK_V1_HOST
          - server: V2
            host: FLASK_V2_HOST

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{secrets[matrix.host]}}
          username: ${{secrets.GENERAL_USER}}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            if [ ! -d "/opt/instagram" ]; then
              echo "Creating /opt/instagram directory..."
              sudo mkdir -p /opt/instagram
              sudo chown -R "${{ secrets.GENERAL_USER }}":"${{ secrets.GENERAL_USER }}" /opt/instagram/
            else
              cd /opt/instagram/
              if [ -f "docker-compose.yml" ]; then
                echo "Stopping existing services..."
                docker compose -f ./docker-compose.yml -f ./docker-compose.prod.yml down --remove-orphans
              fi
              echo "Cleaning directory..."
              rm -f docker-compose.yml docker-compose.prod.yml
            fi

      - name: Copy Configuration Files
        uses: appleboy/scp-action@v1
        with:
          host: ${{secrets[matrix.host]}}
          username: ${{secrets.GENERAL_USER}}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "docker-compose.yml,docker-compose.prod.yml"
          target: "/opt/instagram/"

      - name: Deploy Application
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{secrets[matrix.host]}}
          username: ${{secrets.GENERAL_USER}}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd /opt/instagram/
            chmod 600 docker-compose.yml docker-compose.prod.yml
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            export DOCKER_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/instagram:sha-${{ github.sha }}
            docker compose -f ./docker-compose.yml -f ./docker-compose.prod.yml pull
            docker compose -f ./docker-compose.yml -f ./docker-compose.prod.yml up -d

      - name: Verify Deployment
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{secrets[matrix.host]}}
          username: ${{secrets.GENERAL_USER}}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script_stop: true
          script: |
            cd /opt/instagram/
            export DOCKER_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/instagram:sha-${{ github.sha }}
            if ! docker compose ps | grep -q "Up"; then
              echo "Deployment failed on Flask ${{ matrix.server }}. Checking logs..."
              docker compose logs
              exit 1
            fi
            echo "Deployment on Flask ${{ matrix.server }} verified successfully!"
            docker image prune -f
