# Event: On Pull Request → any branch into develop/main

# Jobs:
#  - Build
#  - Unit Test with matrix
#  - Deploy
# Description:
# This workflow will trigger for any pull request into develop/main. It will build and then test the app with a test matrix. The results of this workflow are visible in the pull request. 
# Afterwards the docker image instagram:stage will be built and pushed to the image repository.


name: Build Pipeline

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  format:
    name: Code Quality Checks
    runs-on: [self-hosted, V1]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8

    - name: Lint with black
      run: black . --check


  # test:
  #   name: Test with Docker Compose
  #   runs-on: [self-hosted, V1]
  #   needs: format

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4

  #   - name: Create env file
  #     run: |
  #       echo "FLASK_APP=app.main" > .env
  #       echo "FLASK_ENV=testing" >> .env
  #       echo "REDIS_URL=redis://redis:6379/0" >> .env

  #   - name: Build and test
  #     run: |
  #       docker compose build
  #       docker compose up -d
  #       # Wait for services to be ready
  #       sleep 10
  #       # Run tests
  #       docker compose exec -T app pytest
        
  #   - name: Cleanup
  #     run: docker compose down