# Event: On Pull Request → any branch into develop/main

# Jobs:
#  - Build
#  - Unit Test with matrix
#  - Deploy
# Description:
# This workflow will trigger for any pull request into develop/main. It will build and then test the app with a test matrix. The results of this workflow are visible in the pull request. 
# Afterwards the docker image instagram:stage will be built and pushed to the image repository.


name: STAGE - CI/CD Pipeline.

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  format:
    name: Black Formatter.
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Black
      run: pip install black

    - name: Lint with black
      run: black . --check

  # test:
  #   name: Test with Python ${{ matrix.python-version }}
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       python-version: ["3.8", "3.9", "3.10", "3.11"]

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4

  #   - name: Set up Python ${{ matrix.python-version }}
  #     uses: actions/setup-python@v4
  #     with:
  #       python-version: ${{ matrix.python-version }}

  #   - name: Install poetry
  #     uses: snok/install-poetry@v1

  #   - name: Install dependencies with Poetry
  #     run: poetry install

  #   - name: Run tests
  #     run: poetry run pytest

  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    needs: format

    steps:
      - name: Checkout Code.
        uses: actions/checkout@v4

      - name: Login with Docker Hub.
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/instagram:latest .

      - name: Docker Push Image
        run: |
          docker push ${{secrets.DOCKERHUB_USERNAME}}/instagram:latest